#!/usr/bin/env python3
"""
Generate basic calibration test G-code files
These are simple patterns that don't require slicing
"""

import os

GCODE_DIR = "/home/pi/printer_data/gcodes/calibration_prints"

def generate_first_layer_squares():
    """Generate 5 first layer test squares"""
    gcode = """
; First Layer Test - 5 Squares
; Generated by calibration system
; Tests: bed adhesion, Z-offset, bed leveling

G21 ; metric values
G90 ; absolute positioning
M82 ; absolute extrusion mode

; Start sequence
G28 ; home all axes
BED_MESH_PROFILE LOAD=default ; load mesh
G1 Z15.0 F6000 ; move the platform down 15mm

; Prime line
G1 X10 Y10 Z0.3 F5000.0 ; move to start position
G1 X150 Y10 Z0.3 F1500.0 E15 ; draw prime line
G1 X150 Y10.3 Z0.3 F5000.0 ; move to side
G1 X10 Y10.3 Z0.3 F1500.0 E30 ; draw second line
G92 E0 ; reset extruder
G1 Z2.0 F3000 ; move Z up

; Layer height: 0.2mm
; Extrusion width: 0.4mm
; Speed: 30mm/s for first layer
; Square size: 40x40mm
; Spacing: 10mm between squares

; Square 1 - Front Left (50, 50)
G1 X50 Y50 Z0.2 F5000
G1 F1800
G1 X90 Y50 E1.5
G1 X90 Y90 E3.0
G1 X50 Y90 E4.5
G1 X50 Y50 E6.0
G1 X52 Y52 ; infill
G1 X88 Y52 E7.3
G1 X88 Y54 E7.4
G1 X52 Y54 E8.7
G1 X52 Y56 E8.8
G1 X88 Y56 E10.1

; Square 2 - Front Right (210, 50)
G1 X210 Y50 Z0.2 F5000
G1 F1800
G1 X250 Y50 E11.5
G1 X250 Y90 E13.0
G1 X210 Y90 E14.5
G1 X210 Y50 E16.0

; Square 3 - Center (130, 130)
G1 X130 Y130 Z0.2 F5000
G1 F1800
G1 X170 Y130 E17.5
G1 X170 Y170 E19.0
G1 X130 Y170 E20.5
G1 X130 Y130 E22.0

; Square 4 - Back Left (50, 210)
G1 X50 Y210 Z0.2 F5000
G1 F1800
G1 X90 Y210 E23.5
G1 X90 Y250 E25.0
G1 X50 Y250 E26.5
G1 X50 Y210 E28.0

; Square 5 - Back Right (210, 210)
G1 X210 Y210 Z0.2 F5000
G1 F1800
G1 X250 Y210 E29.5
G1 X250 Y250 E31.0
G1 X210 Y250 E32.5
G1 X210 Y210 E34.0

; End sequence
G91 ; relative positioning
G1 E-2 F2700 ; retract
G1 Z10 F3000 ; lift nozzle
G90 ; absolute positioning
G28 X Y ; home X and Y
M84 ; disable motors
M106 S0 ; turn off fan
; End of first layer test
"""
    return gcode.strip()

def generate_single_wall_cube():
    """Generate a simple single-wall calibration cube outline"""
    gcode = """
; Single Wall Cube - 20x20x20mm
; Generated by calibration system
; Tests: dimensional accuracy, extrusion multiplier

G21 ; metric values
G90 ; absolute positioning
M82 ; absolute extrusion mode

; Start sequence
G28 ; home all axes
BED_MESH_PROFILE LOAD=default
G1 Z15.0 F6000

; Prime line
G1 X10 Y10 Z0.3 F5000.0
G1 X100 Y10 Z0.3 F1500.0 E10
G92 E0
G1 Z2.0 F3000

; Starting position: center of bed (140, 140)
; Cube size: 20x20mm
; Layer height: 0.2mm
; 100 layers total

"""
    
    # Generate 100 layers
    e_value = 0
    for layer in range(100):
        z_height = 0.2 + (layer * 0.2)
        start_x = 140
        start_y = 140
        
        gcode += f"\n; Layer {layer + 1}\n"
        gcode += f"G1 X{start_x} Y{start_y} Z{z_height:.2f} F5000\n"
        gcode += "G1 F1200\n"
        
        # Draw square perimeter (20x20mm)
        e_value += 0.8
        gcode += f"G1 X{start_x + 20} Y{start_y} E{e_value:.2f}\n"
        e_value += 0.8
        gcode += f"G1 X{start_x + 20} Y{start_y + 20} E{e_value:.2f}\n"
        e_value += 0.8
        gcode += f"G1 X{start_x} Y{start_y + 20} E{e_value:.2f}\n"
        e_value += 0.8
        gcode += f"G1 X{start_x} Y{start_y} E{e_value:.2f}\n"
    
    gcode += """
; End sequence
G91
G1 E-2 F2700
G1 Z10 F3000
G90
G28 X Y
M84
M106 S0
; End of single wall cube
"""
    return gcode.strip()

def generate_bed_level_test():
    """Generate a large first layer for bed level testing"""
    gcode = """
; Bed Level Test - Large First Layer
; Generated by calibration system
; Tests: overall bed flatness and mesh accuracy

G21
G90
M82

; Start sequence
G28
BED_MESH_PROFILE LOAD=default
G1 Z15.0 F6000

; Prime line
G1 X10 Y10 Z0.3 F5000.0
G1 X150 Y10 Z0.3 F1500.0 E15
G92 E0
G1 Z0.2 F3000

; Draw large rectangle covering most of bed
; 280x280mm area (10mm margin)
G1 X10 Y10 Z0.2 F5000
G1 F1200

; Outline
G1 X290 Y10 E10
G1 X290 Y290 E25
G1 X10 Y290 E40
G1 X10 Y10 E55

; Fill with grid pattern
"""
    
    e_value = 55
    # Horizontal lines
    for y in range(20, 280, 20):
        if (y // 20) % 2 == 0:
            gcode += f"G1 X10 Y{y} F5000\nG1 F1200\n"
            e_value += 12
            gcode += f"G1 X290 Y{y} E{e_value:.1f}\n"
        else:
            gcode += f"G1 X290 Y{y} F5000\nG1 F1200\n"
            e_value += 12
            gcode += f"G1 X10 Y{y} E{e_value:.1f}\n"
    
    gcode += """
; End sequence
G91
G1 E-2 F2700
G1 Z10 F3000
G90
G28 X Y
M84
M106 S0
; End of bed level test
"""
    return gcode.strip()

def save_gcode(filename, content):
    """Save gcode to file"""
    filepath = os.path.join(GCODE_DIR, filename)
    with open(filepath, 'w') as f:
        f.write(content)
    print(f"✓ Created: {filename}")

def main():
    print("Generating calibration test G-code files...\n")
    
    # Create directory if it doesn't exist
    os.makedirs(GCODE_DIR, exist_ok=True)
    
    # Generate files
    save_gcode("first_layer_5squares.gcode", generate_first_layer_squares())
    save_gcode("single_wall_cube_20mm.gcode", generate_single_wall_cube())
    save_gcode("bed_level_large.gcode", generate_bed_level_test())
    
    print("\n✅ Done! Generated 3 calibration test files.")
    print("\nThese are basic tests that don't require slicing.")
    print("For more complex tests (temperature towers, etc.), use a slicer.\n")

if __name__ == "__main__":
    main()
